# Generated by Django 5.2.7 on 2025-10-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_grader', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['conference'], name='paper_grade_confere_59220a_idx'),
        ),
    ]
