# Generated by Django 5.2.7 on 2025-11-16 11:03

from django.db import migrations


def add_conference_AAAI26_questions(apps, schema_editor):
    Conference = apps.get_model('paper_grader', 'Conference')
    Question = apps.get_model('paper_grader', 'Question')


    conference, _ = Conference.objects.get_or_create(name='AAAI-26')


    questions = [
        "This paper includes a conceptual outline and/or pseudocode description of AI methods introduced",
        "This paper clearly delineates statements that are opinions, hypothesis, and speculation from objective facts and results",
        "This paper provides well marked pedagogical references for less-familiar readers to gain background necessary to replicate the paper",
        "Does this paper make theoretical contributions?",
        "All assumptions and restrictions are stated clearly and formally.",
        "All novel claims are stated formally (e.g., in theorem statements).",
        "Proofs of all novel claims are included.",
        "Proof sketches or intuitions are given for complex and/or novel results.",
        "Appropriate citations to theoretical tools used are given.",
        "All theoretical claims are demonstrated empirically to hold.",
        "All experimental code used to eliminate or disprove claims is included.",
        "Does this paper rely on one or more datasets?",
        "A motivation is given for why the experiments are conducted on the selected datasets",
        "All novel datasets introduced in this paper are included in a data appendix.",
        "All novel datasets introduced in this paper will be made publicly available upon publication of the paper with a license that allows free usage for research purposes.",
        "All datasets drawn from the existing literature are accompanied by appropriate citations.",
        "All datasets drawn from the existing literature are publicly available.",
        "All datasets that are not publicly available are described in detail, with explanation why publicly available alternatives are not scientifically satisficing.",
        "Does this paper include computational experiments?",
        "This paper states the number and range of values tried per (hyper-)parameter and the criterion used for selecting the final parameter setting.",
        "Any code required for pre-processing data is included in the appendix.",
        "All source code required for conducting and analyzing the experiments is included in a code appendix.",
        "All source code required for conducting and analyzing the experiments will be made publicly available upon publication of the paper with a license that allows free usage for research purposes.",
        "All source code implementing new methods have comments detailing the implementation, with references to the paper where each step comes from.",
        "If an algorithm depends on randomness, then the method used for setting seeds is described in a way sufficient to allow replication of results.",
        "This paper specifies the computing infrastructure used for running experiments (hardware and software), including GPU/CPU models; amount of memory; operating system; names and versions of relevant software libraries and frameworks.",
        "This paper formally describes evaluation metrics used and explains the motivation for choosing these metrics.",
        "This paper states the number of algorithm runs used to compute each reported result.",
        "Analysis of experiments includes distributional information (variation, confidence, etc.).",
        "The significance of any improvement or decrease in performance is judged using appropriate statistical tests.",
        "This paper lists all final (hyper-)parameters used for each model/algorithm in the paper’s experiments.",
    ]


    for i, text in enumerate(questions):
        Question.objects.create(conference=conference, question_text=text, position=i)

    
def remove_conference_AAI26_questions(apps, schema_editor):
    Conference = apps.get_model('paper_grader', 'Conference')
    Question = apps.get_model('paper_grader', 'Question')


    try:
        conference = Conference.objects.get(name='AAAI-26')
        Question.objects.filter(conference=conference).delete()
    except Conference.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('paper_grader', '0003_alter_question_options_question_position_and_more'),
    ]

    operations = [
        migrations.RunPython(add_conference_AAAI26_questions, remove_conference_AAI26_questions),
    ]
