# Generated by Django 5.2.7 on 2026-03-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_grader', '0004_auto_20251116_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
